### ISSUE TITLE
未为 background.html 填入文件编码

### ISSUE THREAD

**Issue by Crystal-RainSlide** [jingyu9575/download-filename-encoding#2]
background.html 文件只含有一个空的 `charset` 属性。应当为 `utf-8`。

![background.html 截图](https://user-images.githubusercontent.com/16851802/79191203-a2192480-7e58-11ea-83da-a5c4b6ff6820.png)

调试 background.html 时可见。

![日志截图](https://user-images.githubusercontent.com/16851802/79191246-ba893f00-7e58-11ea-9feb-a58fba3adc3a.png)

**Comment by jingyu9575** [comment]
在旧版的火狐里，这样做可以检测系统默认的编码，例如在中文环境下自动选择 GBK。
最新版火狐默认编码固定是 windows-1252，检测失效。下次更新我加上 utf-8。
