### ISSUE TITLE
Can I fork it and create it for Safari 14?

### ISSUE THREAD

**Issue by Uhucream** [jingyu9575/download-filename-encoding#3]
As the title suggests, I would like to modify this addon for Safari 14 which supports WebExtensions API.
Can I do?

**Comment by yfdyh000** [comment]
Mozilla Public License, version 2.0 listed on https://addons.mozilla.org/firefox/addon/download-filename-encoding/.

**Comment by Uhucream** [comment]
@yfdyh000 
> Mozilla Public License, version 2.0 listed on https://addons.mozilla.org/firefox/addon/download-filename-encoding/.

So I can convert this addon and release on Mac App Store, can't I ?

**Comment by yfdyh000** [comment]
> @yfdyh000
> 
> > Mozilla Public License, version 2.0 listed on https://addons.mozilla.org/firefox/addon/download-filename-encoding/.
> 
> So I can convert this addon and release on Mac App Store, can't I ?

Yes, you can do it. Check the Conditions, e.g. https://github.com/mlinksva/mpl2-repo/blob/master/LICENSE.

**Comment by jingyu9575** [comment]
Yes you can. I've created the LICENSE file. Check it for the conditions.

![图片](https://user-images.githubusercontent.com/8923139/87292778-e6898e80-c533-11ea-8e17-fdbd0aa29b20.png)
